import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import DiffMatchPatch from 'diff-match-patch';

// The Dart↔JS diff-match-patch interop pin (vault_hist C5, RV5). The
// fixtures are GENERATED BY THE DART SIDE (entropy_hist's pinned recipe:
// diff_main → diff_cleanupEfficiency → patch_make, defaults, patch_toText) and
// consumed here, so a history patch produced by one port applies in the other
// with matching sha256 hashes. The contract is semantic: apply + hash. Today
// the emitted patch TEXT is also byte-identical across ports — asserted below
// so any drift in either dmp port is caught, not silently absorbed.

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const override = join(root, 'spec_sources_overrides.json');
const config = JSON.parse(readFileSync(existsSync(override) ? override : join(root, 'spec_sources.json'), 'utf8'));
const fixtureDir = join(root, config.sources[0], 'packages/entropy_hist/test/hist/fixtures/dmp_interop');

interface DmpFixture {
  before: string;
  after: string;
  patch: string;
  beforeSha: string;
  afterSha: string;
}

function sha256Hex(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

const fixtures: Array<[string, DmpFixture]> = readdirSync(fixtureDir)
  .filter((name) => name.endsWith('.json'))
  .sort()
  .map((name) => [
    name,
    JSON.parse(readFileSync(join(fixtureDir, name), 'utf8')) as DmpFixture,
  ]);

test('fixtures cover plain, unicode, and multi-hunk edits', () => {
  const names = fixtures.map(([name]) => name);
  for (const expected of ['multi_hunk.json', 'plain_edit.json', 'unicode.json']) {
    assert.ok(names.includes(expected), `missing fixture ${expected}`);
  }
  for (const [name, fx] of fixtures) {
    assert.equal(sha256Hex(fx.before), fx.beforeSha, `${name}: beforeSha`);
    assert.equal(sha256Hex(fx.after), fx.afterSha, `${name}: afterSha`);
  }
});

for (const [name, fx] of fixtures) {
  test(`${name}: the Dart-made patch applies here with every hunk and a matching sha256`, () => {
    const dmp = new DiffMatchPatch();
    const patches = dmp.patch_fromText(fx.patch);
    const [result, applied] = dmp.patch_apply(patches, fx.before);
    assert.ok(
      applied.every(Boolean),
      `${name}: every hunk must apply (dmp is fuzzy — a false is a failure)`,
    );
    // The hash is the verdict: dmp can "succeed" fuzzily with garbage, so the
    // reader always verifies sha256 (vault_hist RV5).
    assert.equal(sha256Hex(result), fx.afterSha, `${name}: result sha256`);
    assert.equal(result, fx.after, `${name}: result text`);
  });

  test(`${name}: the pinned JS recipe round-trips before → after`, () => {
    const dmp = new DiffMatchPatch();
    // The pinned recipe, mirroring the Dart writer: diff_main →
    // diff_cleanupEfficiency (default edit cost 4) → patch_make → patch_toText.
    const diffs = dmp.diff_main(fx.before, fx.after);
    dmp.diff_cleanupEfficiency(diffs);
    const patchText = dmp.patch_toText(dmp.patch_make(fx.before, diffs));

    const [result, applied] = dmp.patch_apply(
      dmp.patch_fromText(patchText),
      fx.before,
    );
    assert.ok(applied.every(Boolean), `${name}: every own hunk must apply`);
    assert.equal(sha256Hex(result), fx.afterSha, `${name}: round-trip sha256`);

    // Not required by the contract (apply + sha is), but true today: the JS
    // port emits the exact bytes the Dart port checked in. If this ever fails
    // while apply+sha still pass, the ports have drifted textually — decide
    // deliberately, don't let it slide.
    assert.equal(
      patchText,
      fx.patch,
      `${name}: patch text drifted from the Dart-emitted fixture`,
    );
  });
}
