#!/usr/bin/env bash
#
# Server side of the entropy-sync provisioning (`vault_daemon` Appendix A):
# turn a bare Debian/Ubuntu VPS into the sync hub — CouchDB 3 behind Caddy with
# automatic TLS — and create one vault database with its own non-admin user.
#
# Runs ON the server. `provision.sh` copies it there; you can also run it by
# hand. It is **idempotent**: re-running updates the config and leaves existing
# data, users and databases alone.
#
# Required environment:
#   DOMAIN            the hostname pointing at this server, e.g. sync.example.com
#   ACME_EMAIL        email for Let's Encrypt
#   COUCH_ADMIN_PASS  CouchDB admin password (generated by provision.sh)
#   SYNC_USER_PASS    password for the vault's non-admin user
# Optional:
#   COUCH_ADMIN_USER  default: admin
#   SYNC_USER         default: entropy
#   DATABASE          default: vault
#   INSTALL_DIR       default: /opt/entropy-sync
#   SKIP_DOCKER=1     skip installing/starting containers (configure only)
#   COUCH_URL         where CouchDB answers, default http://127.0.0.1:5984
#
set -euo pipefail

DOMAIN="${DOMAIN:-}"
ACME_EMAIL="${ACME_EMAIL:-}"
COUCH_ADMIN_USER="${COUCH_ADMIN_USER:-admin}"
COUCH_ADMIN_PASS="${COUCH_ADMIN_PASS:-}"
SYNC_USER="${SYNC_USER:-entropy}"
SYNC_USER_PASS="${SYNC_USER_PASS:-}"
DATABASE="${DATABASE:-vault}"
INSTALL_DIR="${INSTALL_DIR:-/opt/entropy-sync}"
COUCH_URL="${COUCH_URL:-http://127.0.0.1:5984}"
SKIP_DOCKER="${SKIP_DOCKER:-0}"

need() { [[ -n "${!1:-}" ]] || { echo "error: $1 is required" >&2; exit 2; }; }
need COUCH_ADMIN_PASS
need SYNC_USER_PASS
if [[ "$SKIP_DOCKER" != "1" ]]; then
  need DOMAIN
  need ACME_EMAIL
fi

say() { echo "==> $*"; }
ADMIN_AUTH="$COUCH_ADMIN_USER:$COUCH_ADMIN_PASS"

# --- containers ---------------------------------------------------------------
if [[ "$SKIP_DOCKER" != "1" ]]; then
  if ! command -v docker >/dev/null 2>&1; then
    say "installing docker"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl >/dev/null
    curl -fsSL https://get.docker.com | sh >/dev/null
  fi
  say "writing $INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"/{couchdb-data,couchdb-etc,caddy-data,caddy-config}
  # CouchDB in its container runs as uid/gid 5984.
  chown -R 5984:5984 "$INSTALL_DIR/couchdb-data" "$INSTALL_DIR/couchdb-etc"

  cat > "$INSTALL_DIR/.env" <<ENV
COUCHDB_USER=$COUCH_ADMIN_USER
COUCHDB_PASSWORD=$COUCH_ADMIN_PASS
ENV
  chmod 600 "$INSTALL_DIR/.env"

  cat > "$INSTALL_DIR/docker-compose.yml" <<'COMPOSE'
services:
  couchdb:
    image: couchdb:3
    container_name: entropy-couchdb
    restart: unless-stopped
    user: "5984:5984"
    env_file: [.env]
    volumes:
      - ./couchdb-data:/opt/couchdb/data
      - ./couchdb-etc:/opt/couchdb/etc/local.d
    ports:
      - "127.0.0.1:5984:5984"   # never exposed directly; Caddy fronts it

  caddy:
    image: caddy:2
    container_name: entropy-caddy
    restart: unless-stopped
    depends_on: [couchdb]
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data
      - ./caddy-config:/config
COMPOSE

  cat > "$INSTALL_DIR/Caddyfile" <<CADDY
{
	email $ACME_EMAIL
}

$DOMAIN {
	reverse_proxy couchdb:5984
}
CADDY

  say "starting containers"
  (cd "$INSTALL_DIR" && docker compose up -d)
fi

# --- wait for CouchDB ---------------------------------------------------------
say "waiting for CouchDB at $COUCH_URL"
for _ in $(seq 1 60); do
  if curl -fsS -u "$ADMIN_AUTH" "$COUCH_URL/" >/dev/null 2>&1; then break; fi
  sleep 2
done
curl -fsS -u "$ADMIN_AUTH" "$COUCH_URL/" >/dev/null

# --- one-time cluster + server settings ---------------------------------------
# Idempotent: a second run just re-applies the same values.
say "configuring CouchDB"
curl -fsS -u "$ADMIN_AUTH" -X POST "$COUCH_URL/_cluster_setup" \
  -H 'Content-Type: application/json' \
  -d "{\"action\":\"enable_single_node\",\"username\":\"$COUCH_ADMIN_USER\",\"password\":\"$COUCH_ADMIN_PASS\",\"bind_address\":\"0.0.0.0\",\"port\":5984,\"singlenode\":true}" \
  >/dev/null 2>&1 || true   # already-configured node answers 400; that is fine

cfg() { # cfg <path> <json-value>
  curl -fsS -u "$ADMIN_AUTH" -X PUT "$COUCH_URL/_node/_local/_config/$1" \
    -H 'Content-Type: application/json' -d "$2" >/dev/null
}
# Every request must authenticate — the hub is public.
cfg chttpd/require_valid_user '"true"'
cfg chttpd_auth/require_valid_user '"true"'
cfg httpd/WWW-Authenticate '"Basic realm=\"couchdb\""'
# Attachments stream whole (`vault_sync` R7): the request cap must be generous,
# while document bodies stay ~1.4 MB at most.
cfg chttpd/max_http_request_size '"4294967296"'
cfg couchdb/max_document_size '"50000000"'
# `_revs_limit` is deliberately left at its default 1000 — it is the offline
# merge engine, not bloat (`vault_sync` C7).

# --- the vault's database and its own non-admin user --------------------------
say "creating database \"$DATABASE\""
code=$(curl -sS -u "$ADMIN_AUTH" -o /dev/null -w '%{http_code}' \
  -X PUT "$COUCH_URL/$DATABASE")
case "$code" in
  201|202) echo "    created" ;;
  412) echo "    already exists — left as is" ;;
  *) echo "error: creating $DATABASE failed (HTTP $code)" >&2; exit 1 ;;
esac

say "creating user \"$SYNC_USER\""
user_doc="$COUCH_URL/_users/org.couchdb.user:$SYNC_USER"
code=$(curl -sS -u "$ADMIN_AUTH" -o /dev/null -w '%{http_code}' \
  -X PUT "$user_doc" -H 'Content-Type: application/json' \
  -d "{\"name\":\"$SYNC_USER\",\"password\":\"$SYNC_USER_PASS\",\"roles\":[],\"type\":\"user\"}")
case "$code" in
  201|202) echo "    created" ;;
  409)
    # The user is already there and its password cannot be read back. Rotating
    # it would lock out every device already configured with the old one, so
    # that only happens on explicit request.
    if [[ "${ROTATE_SYNC_PASSWORD:-0}" == "1" ]]; then
      rev=$(curl -fsS -u "$ADMIN_AUTH" "$user_doc" \
        | sed -n 's/.*"_rev":"\([^"]*\)".*/\1/p')
      curl -fsS -u "$ADMIN_AUTH" -X PUT "$user_doc" \
        -H 'Content-Type: application/json' -H "If-Match: $rev" \
        -d "{\"name\":\"$SYNC_USER\",\"password\":\"$SYNC_USER_PASS\",\"roles\":[],\"type\":\"user\"}" \
        >/dev/null
      echo "    already existed — password rotated (devices configured with"
      echo "    the old password must be set up again)"
    else
      echo "    already exists — password left unchanged"
      REUSED_EXISTING_USER=1
    fi
    ;;
  *) echo "error: creating $SYNC_USER failed (HTTP $code)" >&2; exit 1 ;;
esac

# Only this user may read or write this database (no admins beyond the server
# admin, no roles).
say "restricting \"$DATABASE\" to \"$SYNC_USER\""
curl -fsS -u "$ADMIN_AUTH" -X PUT "$COUCH_URL/$DATABASE/_security" \
  -H 'Content-Type: application/json' \
  -d "{\"admins\":{\"names\":[],\"roles\":[]},\"members\":{\"names\":[\"$SYNC_USER\"],\"roles\":[]}}" \
  >/dev/null

# --- verify the way a client will use it --------------------------------------
say "verifying"
if ! curl -fsS -u "$SYNC_USER:$SYNC_USER_PASS" "$COUCH_URL/$DATABASE" >/dev/null
then
  if [[ "${REUSED_EXISTING_USER:-0}" == "1" ]]; then
    cat >&2 <<MSG
error: the user "$SYNC_USER" already existed on this server, so the password
       generated now does not fit it. CouchDB cannot reveal an existing
       password — do one of:
         • re-run passing the password you already have:
             --sync-password '<the existing one>'
         • or set ROTATE_SYNC_PASSWORD=1 to replace it (every device already
           configured with the old password will have to be set up again).
MSG
  else
    echo "error: $SYNC_USER cannot read $DATABASE" >&2
  fi
  exit 1
fi
if curl -fsS -u "$SYNC_USER:$SYNC_USER_PASS" "$COUCH_URL/_users/_all_docs" \
     >/dev/null 2>&1; then
  echo "warning: $SYNC_USER can read _users — expected a 403" >&2
fi

echo "OK ${DOMAIN:-$COUCH_URL} $DATABASE $SYNC_USER"
